exclude = []
source_roots = [
    "src",
]
exact = true
forbid_circular_dependencies = true

[[modules]]
path = "hub_api.api"
depends_on = [
    "hub_api.dependencies",
    "hub_api.enums",
    "hub_api.ids",
    "hub_api.schemas",
]

[[modules]]
path = "hub_api.client"
depends_on = [
    "hub_api.enums",
    "hub_api.exceptions",
    "hub_api.ids",
    "hub_api.schemas",
]

[[modules]]
path = "hub_api.dependencies"
depends_on = [
    "hub_api.client",
    "hub_api.database",
]

[[modules]]
path = "hub_api.enums"
depends_on = []

[[modules]]
path = "hub_api.exceptions"
depends_on = []

[[modules]]
path = "hub_api.helpers.etag"
depends_on = []

[[modules]]
path = "hub_api.ids"
depends_on = [
    "hub_api.enums",
    "hub_api.exceptions",
]

[[modules]]
path = "hub_api.main"
depends_on = [
    "hub_api.api",
    "hub_api.exceptions",
    "hub_api.helpers.etag",
]

[[modules]]
path = "hub_api.schemas"
depends_on = [
    "hub_api.enums",
]

[[modules]]
path = "hub_api.static"
depends_on = []

[[modules]]
path = "hub_api.database"
depends_on = []

[[interfaces]]
expose = [
    "api",
    "meltano",
    "validation",
]
from = [
    "hub_api.schemas",
]
