from __future__ import annotations

from typing import Any, Required, TypedDict
lazy from collections.abc import Sequence

from pydantic import MISSING, BaseModel, ConfigDict, Field, with_config


class Problem(BaseModel):
    type: str = Field(description="URI reference that identifies the problem type")
    status: int = Field(description="Number indicating the HTTP status generated by the origin server")
    title: str = Field(description="String containing a short, human-readable summary of the problem type")

    detail: str | MISSING = Field(
        default=MISSING,
        description="String containing a human-readable explanation specific to this occurrence of the problem",
    )

    instance: str | MISSING = Field(
        default=MISSING,
        description="String containing a URI reference that identifies the specific occurrence of the problem",
    )


# TODO: Remove Pyright comments: https://github.com/microsoft/pyright/issues/11742
_FIELD_TITLE_MAPPING = frozendict(
    ctx="Context",  # pyrefly: ignore[unexpected-keyword]  # pyright: ignore[reportCallIssue]
    input="Input",  # pyrefly: ignore[unexpected-keyword]  # pyright: ignore[reportCallIssue]
    loc="Location",  # pyrefly: ignore[unexpected-keyword]  # pyright: ignore[reportCallIssue]
    msg="Message",  # pyrefly: ignore[unexpected-keyword]  # pyright: ignore[reportCallIssue]
    type="Error Type",  # pyrefly: ignore[unexpected-keyword]  # pyright: ignore[reportCallIssue]
)


@with_config(ConfigDict(field_title_generator=lambda n, _fi: _FIELD_TITLE_MAPPING[n]))
class ValidationError(TypedDict, total=False):
    ctx: dict  # type: ignore[type-arg] # pyrefly: ignore[implicit-any-type-argument]
    input: Any
    loc: Required[list[str | int]]
    msg: Required[str]
    type: Required[str]


class ValidationErrorProblem(Problem):
    errors: Sequence[ValidationError] = Field(
        default_factory=list,
        description="Custom extension to the RFC 9457 schema detailing validation errors",
    )
